package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseAnswerLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AnswerLog extends BaseAnswerLog<AnswerLog> {
	public static final AnswerLog dao = new AnswerLog().dao();
}
