package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Answer extends BaseAnswer<Answer> {
	public static final Answer dao = new Answer().dao();
}
