package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseAskList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AskList extends BaseAskList<AskList> {
	public static final AskList dao = new AskList().dao();
}
