package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseAskRunLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AskRunLog extends BaseAskRunLog<AskRunLog> {
	public static final AskRunLog dao = new AskRunLog().dao();
}
