package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseBaseMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMsg extends BaseBaseMsg<BaseMsg> {
	public static final BaseMsg dao = new BaseMsg().dao();
}
