package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseBaseFlowMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseFlowMsg extends BaseBaseFlowMsg<BaseFlowMsg> {
	public static final BaseFlowMsg dao = new BaseFlowMsg().dao();
}
