package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseBaseFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseFlow extends BaseBaseFlow<BaseFlow> {
	public static final BaseFlow dao = new BaseFlow().dao();
}
