package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseBug;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bug extends BaseBug<Bug> {
	public static final Bug dao = new Bug().dao();
}
