package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseExamQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamQuestion extends BaseExamQuestion<ExamQuestion> {
	public static final ExamQuestion dao = new ExamQuestion().dao();
}
