package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseExamUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamUser extends BaseExamUser<ExamUser> {
	public static final ExamUser dao = new ExamUser().dao();
}
