package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseExam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exam extends BaseExam<Exam> {
	public static final Exam dao = new Exam().dao();
}
