package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseMsgTemplet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgTemplet extends BaseMsgTemplet<MsgTemplet> {
	public static final MsgTemplet dao = new MsgTemplet().dao();
}
