package com.jfinal.club.common.model;

import com.cjih.learnsystem.controller.ResourceInfoController;
import com.jfinal.club.common.model.base.BaseMsgTempletSub;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgTempletSub extends BaseMsgTempletSub<MsgTempletSub> {
	public static final MsgTempletSub dao = new MsgTempletSub().dao();
	
	public String getUnitTypeView(){
		return ResourceInfoController.getResourceName("PUB001", (String)get("unit_type"));//.dao.getfind("select * from trole where id in (select role_id from tuser_trole where user_id = '"+get("id")+"')");
	
	}
	
	public String getUnitView(){
		return Db.queryStr("select unit_desc from tunit where id = '"+get("unit_id")+"'");//.dao.getfind("select * from trole where id in (select role_id from tuser_trole where user_id = '"+get("id")+"')");
	
	}
	
	public String getMsgTypeView(){
		return ResourceInfoController.getResourceName("PUB007", (String)get("msg_type"));//.dao.getfind("select * from trole where id in (select role_id from tuser_trole where user_id = '"+get("id")+"')");
	
	}
}
