package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Number extends BaseNumber<Number> {
	public static final Number dao = new Number().dao();
}
