package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseOnline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Online extends BaseOnline<Online> {
	public static final Online dao = new Online().dao();
}
