package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseQuestionCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionCopy1 extends BaseQuestionCopy1<QuestionCopy1> {
	
}
