package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseQuestionFlow;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionFlow extends BaseQuestionFlow<QuestionFlow> {
	public static final QuestionFlow dao = new QuestionFlow().dao();

	public String getUnitName(){
		return Db.queryStr("select unit_desc from tunit where id='"+get("unit_id")+"'" );
	}
}
