package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseQuestionFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionFlow extends BaseQuestionFlow<QuestionFlow> {
	public static final QuestionFlow dao = new QuestionFlow().dao();
}
