package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseResourceInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResourceInfo extends BaseResourceInfo<ResourceInfo> {
	public static final ResourceInfo dao = new ResourceInfo().dao();
}
