package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseResourceInfoCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResourceInfoCopy1 extends BaseResourceInfoCopy1<ResourceInfoCopy1> {
	public static final ResourceInfoCopy1 dao = new ResourceInfoCopy1().dao();
}
