package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseResourceType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResourceType extends BaseResourceType<ResourceType> {
	public static final ResourceType dao = new ResourceType().dao();
}
