package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseSavedAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SavedAnswer extends BaseSavedAnswer<SavedAnswer> {
	public static final SavedAnswer dao = new SavedAnswer().dao();
	
	
}
