package com.jfinal.club.common.model;

import com.cjih.learnsystem.controller.ResourceInfoController;
import com.jfinal.club.common.model.base.BaseTrueUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrueUnit extends BaseTrueUnit<TrueUnit> {
	public static final TrueUnit dao = new TrueUnit().dao();
	
	public String getUnitTypeView(){
		return ResourceInfoController.getResourceName("PUB001", (String)get("unit_type"));//.dao.getfind("select * from trole where id in (select role_id from tuser_trole where user_id = '"+get("id")+"')");
	
	}
}
