package com.jfinal.club.common.model;

import com.jfinal.club.common.model.base.BaseUserTrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTrole extends BaseUserTrole<UserTrole> {
	
}
