package com.jfinal.club.common.model;

import com.cjih.learnsystem.controller.ResourceInfoController;
import com.jfinal.club.common.model.base.BaseX1msg;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class X1msg extends BaseX1msg<X1msg> {
	public static final X1msg dao = new X1msg().dao();

	public String getUnitIdView() {
		return Db.queryStr("select unit_desc from tunit where id= '"+get("unit")+"'");
//		return ResourceInfoController.getResourceName("PUB001", (String)get("unit"));
	}
}
