package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRemind<M extends BaseRemind<M>> extends Model<M> implements IBean {

	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}
	
	public Integer getAccountId() {
		return getInt("accountId");
	}

	public void setReferMe(Integer referMe) {
		set("referMe", referMe);
	}
	
	public Integer getReferMe() {
		return getInt("referMe");
	}

	public void setMessage(Integer message) {
		set("message", message);
	}
	
	public Integer getMessage() {
		return getInt("message");
	}

	public void setFans(Integer fans) {
		set("fans", fans);
	}
	
	public Integer getFans() {
		return getInt("fans");
	}

}
