package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgTemplet<M extends BaseMsgTemplet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTempletName(java.lang.String templetName) {
		set("templet_name", templetName);
	}
	
	public java.lang.String getTempletName() {
		return getStr("templet_name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setLicId(java.lang.String licId) {
		set("lic_id", licId);
	}
	
	public java.lang.String getLicId() {
		return getStr("lic_id");
	}

	public void setMsisdn(java.lang.String msisdn) {
		set("msisdn", msisdn);
	}
	
	public java.lang.String getMsisdn() {
		return getStr("msisdn");
	}

	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}
	
	public java.lang.String getImei() {
		return getStr("imei");
	}

	public void setImsi(java.lang.String imsi) {
		set("imsi", imsi);
	}
	
	public java.lang.String getImsi() {
		return getStr("imsi");
	}

	public void setProposeType(java.lang.String proposeType) {
		set("propose_type", proposeType);
	}
	
	public java.lang.String getProposeType() {
		return getStr("propose_type");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setEventSn(java.lang.String eventSn) {
		set("event_sn", eventSn);
	}
	
	public java.lang.String getEventSn() {
		return getStr("event_sn");
	}

	public void setCallSn(java.lang.Integer callSn) {
		set("call_sn", callSn);
	}
	
	public java.lang.Integer getCallSn() {
		return getInt("call_sn");
	}

	public void setCallSnChild(java.lang.Integer callSnChild) {
		set("call_sn_child", callSnChild);
	}
	
	public java.lang.Integer getCallSnChild() {
		return getInt("call_sn_child");
	}

	public void setGummeid(java.lang.String gummeid) {
		set("gummeid", gummeid);
	}
	
	public java.lang.String getGummeid() {
		return getStr("gummeid");
	}

	public void setLai(java.lang.String lai) {
		set("lai", lai);
	}
	
	public java.lang.String getLai() {
		return getStr("lai");
	}

	public void setLastVisitedTai(java.lang.String lastVisitedTai) {
		set("last_visited_tai", lastVisitedTai);
	}
	
	public java.lang.String getLastVisitedTai() {
		return getStr("last_visited_tai");
	}

	public void setTaiList(java.lang.String taiList) {
		set("tai_list", taiList);
	}
	
	public java.lang.String getTaiList() {
		return getStr("tai_list");
	}

	public void setEcgi(java.lang.String ecgi) {
		set("ecgi", ecgi);
	}
	
	public java.lang.String getEcgi() {
		return getStr("ecgi");
	}

	public void setOldMmeSgsn(java.lang.String oldMmeSgsn) {
		set("old_mme_sgsn", oldMmeSgsn);
	}
	
	public java.lang.String getOldMmeSgsn() {
		return getStr("old_mme_sgsn");
	}

	public void setGuti(java.lang.String guti) {
		set("guti", guti);
	}
	
	public java.lang.String getGuti() {
		return getStr("guti");
	}

}
