package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgTempletSub<M extends BaseMsgTempletSub<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setTempletId(Integer templetId) {
		set("templet_id", templetId);
	}

	public Integer getTempletId() {
		return get("templet_id");
	}

	public void setTaxis(Integer taxis) {
		set("taxis", taxis);
	}

	public Integer getTaxis() {
		return get("taxis");
	}

	public void setUnitId(String unitId) {
		set("unit_id", unitId);
	}

	public String getUnitId() {
		return get("unit_id");
	}

	public void setMsg(String msg) {
		set("msg", msg);
	}

	public String getMsg() {
		return get("msg");
	}

	public void setLicId(String licId) {
		set("lic_id", licId);
	}

	public String getLicId() {
		return get("lic_id");
	}

	public void setPort(String port) {
		set("port", port);
	}

	public String getPort() {
		return get("port");
	}

	public void setDirection(String direction) {
		set("direction", direction);
	}

	public String getDirection() {
		return get("direction");
	}

	public void setNeX2Addr(String neX2Addr) {
		set("ne_x2_addr", neX2Addr);
	}

	public String getNeX2Addr() {
		return get("ne_x2_addr");
	}

	public void setMsgType(String msgType) {
		set("msg_type", msgType);
	}

	public String getMsgType() {
		return get("msg_type");
	}

	public void setPerposeId(String perposeId) {
		set("perpose_id", perposeId);
	}

	public String getPerposeId() {
		return get("perpose_id");
	}

	public void setRelation1(String relation1) {
		set("relation1", relation1);
	}

	public String getRelation1() {
		return get("relation1");
	}

	public void setRelation2(String relation2) {
		set("relation2", relation2);
	}

	public String getRelation2() {
		return get("relation2");
	}

	public void setEventSn(String eventSn) {
		set("event_sn", eventSn);
	}

	public String getEventSn() {
		return get("event_sn");
	}

	public void setCallSn(String callSn) {
		set("call_sn", callSn);
	}

	public String getCallSn() {
		return get("call_sn");
	}

	public void setCallSnChild(String callSnChild) {
		set("call_sn_child", callSnChild);
	}

	public String getCallSnChild() {
		return get("call_sn_child");
	}

	public void setEventTime(java.util.Date eventTime) {
		set("event_time", eventTime);
	}

	public java.util.Date getEventTime() {
		return get("event_time");
	}

	public void setPerposeType(String perposeType) {
		set("perpose_type", perposeType);
	}

	public String getPerposeType() {
		return get("perpose_type");
	}

	public void setLicX3Addr(String licX3Addr) {
		set("lic_x3_addr", licX3Addr);
	}

	public String getLicX3Addr() {
		return get("lic_x3_addr");
	}

	public void setMsgSn(String msgSn) {
		set("msg_sn", msgSn);
	}

	public String getMsgSn() {
		return get("msg_sn");
	}

	public void setOppositeAddr(String oppositeAddr) {
		set("opposite_addr", oppositeAddr);
	}

	public String getOppositeAddr() {
		return get("opposite_addr");
	}

	public void setOperationResult(String operationResult) {
		set("operation_result", operationResult);
	}

	public String getOperationResult() {
		return get("operation_result");
	}

	public void setFileName(String fileName) {
		set("file_name", fileName);
	}

	public String getFileName() {
		return get("file_name");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setMsgArriveTime(java.util.Date msgArriveTime) {
		set("msg_arrive_time", msgArriveTime);
	}

	public java.util.Date getMsgArriveTime() {
		return get("msg_arrive_time");
	}

}
