package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExam<M extends BaseExam<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setExamName(String examName) {
		set("exam_name", examName);
	}

	public String getExamName() {
		return get("exam_name");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setScore(Integer score) {
		set("score", score);
	}

	public Integer getScore() {
		return get("score");
	}

	public void setIsReadonly(String isReadonly) {
		set("is_readonly", isReadonly);
	}

	public String getIsReadonly() {
		return get("is_readonly");
	}

}
