package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResourceInfoCopy1<M extends BaseResourceInfoCopy1<M>> extends Model<M> implements IBean {

	public void setResourceId(java.lang.String resourceId) {
		set("resource_id", resourceId);
	}
	
	public java.lang.String getResourceId() {
		return getStr("resource_id");
	}

	public void setTypeId(java.lang.String typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.String getTypeId() {
		return getStr("type_id");
	}

	public void setResourceName(java.lang.String resourceName) {
		set("resource_name", resourceName);
	}
	
	public java.lang.String getResourceName() {
		return getStr("resource_name");
	}

	public void setTaxis(java.lang.Integer taxis) {
		set("taxis", taxis);
	}
	
	public java.lang.Integer getTaxis() {
		return getInt("taxis");
	}

	public void setPTypeId(java.lang.String pTypeId) {
		set("p_type_id", pTypeId);
	}
	
	public java.lang.String getPTypeId() {
		return getStr("p_type_id");
	}

	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

}
