package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreatedatetime(java.util.Date createdatetime) {
		set("createdatetime", createdatetime);
	}

	public java.util.Date getCreatedatetime() {
		return get("createdatetime");
	}

	public void setModifydatetime(java.util.Date modifydatetime) {
		set("modifydatetime", modifydatetime);
	}

	public java.util.Date getModifydatetime() {
		return get("modifydatetime");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPwd(String pwd) {
		set("pwd", pwd);
	}

	public String getPwd() {
		return get("pwd");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setEmployeeid(String employeeid) {
		set("employeeid", employeeid);
	}

	public String getEmployeeid() {
		return get("employeeid");
	}

}
