package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseFlowMsg<M extends BaseBaseFlowMsg<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setFlowId(Integer flowId) {
		set("flow_id", flowId);
	}

	public Integer getFlowId() {
		return get("flow_id");
	}

	public void setPort(String port) {
		set("port", port);
	}

	public String getPort() {
		return get("port");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setMsg(String msg) {
		set("msg", msg);
	}

	public String getMsg() {
		return get("msg");
	}

	public void setTaxis(Integer taxis) {
		set("taxis", taxis);
	}

	public Integer getTaxis() {
		return get("taxis");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(String modifyBy) {
		set("modify_by", modifyBy);
	}

	public String getModifyBy() {
		return get("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setUnitId(String unitId) {
		set("unit_id", unitId);
	}

	public String getUnitId() {
		return get("unit_id");
	}

	public void setDirection(String direction) {
		set("direction", direction);
	}

	public String getDirection() {
		return get("direction");
	}

	public void setMsgType(String msgType) {
		set("msg_type", msgType);
	}

	public String getMsgType() {
		return get("msg_type");
	}

}
