package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}
	
	public Integer getAccountId() {
		return getInt("accountId");
	}

	public void setExpireAt(Long expireAt) {
		set("expireAt", expireAt);
	}
	
	public Long getExpireAt() {
		return getLong("expireAt");
	}

}
