package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShareReply<M extends BaseShareReply<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setShareId(Integer shareId) {
		set("shareId", shareId);
	}
	
	public Integer getShareId() {
		return getInt("shareId");
	}

	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}
	
	public Integer getAccountId() {
		return getInt("accountId");
	}

	public void setContent(String content) {
		set("content", content);
	}
	
	public String getContent() {
		return getStr("content");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setReport(Integer report) {
		set("report", report);
	}
	
	public Integer getReport() {
		return getInt("report");
	}

}
