package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNumber<M extends BaseNumber<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMsisdn(String msisdn) {
		set("msisdn", msisdn);
	}

	public String getMsisdn() {
		return get("msisdn");
	}

	public void setImsi(String imsi) {
		set("imsi", imsi);
	}

	public String getImsi() {
		return get("imsi");
	}

	public void setImei(String imei) {
		set("imei", imei);
	}

	public String getImei() {
		return get("imei");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return get("unit");
	}

	public void setNumberFormat(String numberFormat) {
		set("number_format", numberFormat);
	}

	public String getNumberFormat() {
		return get("number_format");
	}

	public void setLicId(String licId) {
		set("lic_id", licId);
	}

	public String getLicId() {
		return get("lic_id");
	}

}
