package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShare<M extends BaseShare<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setAccountId(Integer accountId) {
		set("accountId", accountId);
	}
	
	public Integer getAccountId() {
		return getInt("accountId");
	}

	public void setProjectId(Integer projectId) {
		set("projectId", projectId);
	}
	
	public Integer getProjectId() {
		return getInt("projectId");
	}

	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public void setContent(String content) {
		set("content", content);
	}
	
	public String getContent() {
		return getStr("content");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setClickCount(Integer clickCount) {
		set("clickCount", clickCount);
	}
	
	public Integer getClickCount() {
		return getInt("clickCount");
	}

	public void setReport(Integer report) {
		set("report", report);
	}
	
	public Integer getReport() {
		return getInt("report");
	}

	public void setLikeCount(Integer likeCount) {
		set("likeCount", likeCount);
	}
	
	public Integer getLikeCount() {
		return getInt("likeCount");
	}

	public void setFavoriteCount(Integer favoriteCount) {
		set("favoriteCount", favoriteCount);
	}
	
	public Integer getFavoriteCount() {
		return getInt("favoriteCount");
	}

}
