package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseX2msg<M extends BaseX2msg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setUnitRole(java.lang.String unitRole) {
		set("unit_role", unitRole);
	}
	
	public java.lang.String getUnitRole() {
		return getStr("unit_role");
	}

	public void setNeX2Addr(java.lang.String neX2Addr) {
		set("ne_x2_addr", neX2Addr);
	}
	
	public java.lang.String getNeX2Addr() {
		return getStr("ne_x2_addr");
	}

	public void setMsgType(java.lang.String msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.String getMsgType() {
		return getStr("msg_type");
	}

	public void setPerposeId(java.lang.String perposeId) {
		set("perpose_id", perposeId);
	}
	
	public java.lang.String getPerposeId() {
		return getStr("perpose_id");
	}

	public void setRelation1(java.lang.String relation1) {
		set("relation1", relation1);
	}
	
	public java.lang.String getRelation1() {
		return getStr("relation1");
	}

	public void setRelation2(java.lang.String relation2) {
		set("relation2", relation2);
	}
	
	public java.lang.String getRelation2() {
		return getStr("relation2");
	}

	public void setEventSn(java.lang.String eventSn) {
		set("event_sn", eventSn);
	}
	
	public java.lang.String getEventSn() {
		return getStr("event_sn");
	}

	public void setCallSn(java.lang.String callSn) {
		set("call_sn", callSn);
	}
	
	public java.lang.String getCallSn() {
		return getStr("call_sn");
	}

	public void setCallSnChild(java.lang.String callSnChild) {
		set("call_sn_child", callSnChild);
	}
	
	public java.lang.String getCallSnChild() {
		return getStr("call_sn_child");
	}

	public void setEventTime(java.util.Date eventTime) {
		set("event_time", eventTime);
	}
	
	public java.util.Date getEventTime() {
		return get("event_time");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setPerposeType(java.lang.String perposeType) {
		set("perpose_type", perposeType);
	}
	
	public java.lang.String getPerposeType() {
		return getStr("perpose_type");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setSn1(java.lang.Integer sn1) {
		set("sn1", sn1);
	}
	
	public java.lang.Integer getSn1() {
		return getInt("sn1");
	}

	public void setSn2(java.lang.Integer sn2) {
		set("sn2", sn2);
	}
	
	public java.lang.Integer getSn2() {
		return getInt("sn2");
	}

}
