package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExamQuestion<M extends BaseExamQuestion<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setExamId(Long examId) {
		set("exam_id", examId);
	}

	public Long getExamId() {
		return get("exam_id");
	}

	public void setQuestionId(Long questionId) {
		set("question_id", questionId);
	}

	public Long getQuestionId() {
		return get("question_id");
	}

}
