package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReferMe<M extends BaseReferMe<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setReferAccountId(Integer referAccountId) {
		set("referAccountId", referAccountId);
	}
	
	public Integer getReferAccountId() {
		return getInt("referAccountId");
	}

	public void setNewsFeedId(Integer newsFeedId) {
		set("newsFeedId", newsFeedId);
	}
	
	public Integer getNewsFeedId() {
		return getInt("newsFeedId");
	}

	public void setType(Integer type) {
		set("type", type);
	}
	
	public Integer getType() {
		return getInt("type");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

}
