package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrueUnit<M extends BaseTrueUnit<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setUnitId(String unitId) {
		set("unit_id", unitId);
	}

	public String getUnitId() {
		return get("unit_id");
	}

	public void setX1Ip(String x1Ip) {
		set("x1_ip", x1Ip);
	}

	public String getX1Ip() {
		return get("x1_ip");
	}

	public void setX1Port(String x1Port) {
		set("x1_port", x1Port);
	}

	public String getX1Port() {
		return get("x1_port");
	}

	public void setUnitDesc(String unitDesc) {
		set("unit_desc", unitDesc);
	}

	public String getUnitDesc() {
		return get("unit_desc");
	}

	public void setLicId(String licId) {
		set("lic_id", licId);
	}

	public String getLicId() {
		return get("lic_id");
	}

	public void setLicIp(String licIp) {
		set("lic_ip", licIp);
	}

	public String getLicIp() {
		return get("lic_ip");
	}

	public void setX2Port(String x2Port) {
		set("x2_port", x2Port);
	}

	public String getX2Port() {
		return get("x2_port");
	}

	public void setX3Port(String x3Port) {
		set("x3_port", x3Port);
	}

	public String getX3Port() {
		return get("x3_port");
	}

	public void setExtX3Ip(String extX3Ip) {
		set("ext_x3_ip", extX3Ip);
	}

	public String getExtX3Ip() {
		return get("ext_x3_ip");
	}

	public void setExtX3Port(String extX3Port) {
		set("ext_x3_port", extX3Port);
	}

	public String getExtX3Port() {
		return get("ext_x3_port");
	}

	public void setX1Kt(String x1Kt) {
		set("x1_kt", x1Kt);
	}

	public String getX1Kt() {
		return get("x1_kt");
	}

	public void setX1Sqn(String x1Sqn) {
		set("x1_sqn", x1Sqn);
	}

	public String getX1Sqn() {
		return get("x1_sqn");
	}

	public void setX1Pwd(String x1Pwd) {
		set("x1_pwd", x1Pwd);
	}

	public String getX1Pwd() {
		return get("x1_pwd");
	}

	public void setX2Kt(String x2Kt) {
		set("x2_kt", x2Kt);
	}

	public String getX2Kt() {
		return get("x2_kt");
	}

	public void setX2Sqn(String x2Sqn) {
		set("x2_sqn", x2Sqn);
	}

	public String getX2Sqn() {
		return get("x2_sqn");
	}

	public void setX2Pwd(String x2Pwd) {
		set("x2_pwd", x2Pwd);
	}

	public String getX2Pwd() {
		return get("x2_pwd");
	}

	public void setUnitStatus(String unitStatus) {
		set("unit_status", unitStatus);
	}

	public String getUnitStatus() {
		return get("unit_status");
	}

	public void setX1Status(String x1Status) {
		set("x1_status", x1Status);
	}

	public String getX1Status() {
		return get("x1_status");
	}

	public void setX2Status(String x2Status) {
		set("x2_status", x2Status);
	}

	public String getX2Status() {
		return get("x2_status");
	}

	public void setX3Status(String x3Status) {
		set("x3_status", x3Status);
	}

	public String getX3Status() {
		return get("x3_status");
	}

	public void setUnitType(String unitType) {
		set("unit_type", unitType);
	}

	public String getUnitType() {
		return get("unit_type");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(String modifyBy) {
		set("modify_by", modifyBy);
	}

	public String getModifyBy() {
		return get("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
