package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseX1msg<M extends BaseX1msg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setMsgType(java.lang.String msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.String getMsgType() {
		return getStr("msg_type");
	}

	public void setPerposeId(java.lang.String perposeId) {
		set("perpose_id", perposeId);
	}
	
	public java.lang.String getPerposeId() {
		return getStr("perpose_id");
	}

	public void setOperationResult(java.lang.String operationResult) {
		set("operation_result", operationResult);
	}
	
	public java.lang.String getOperationResult() {
		return getStr("operation_result");
	}

	public void setMsgArriveTime(java.util.Date msgArriveTime) {
		set("msg_arrive_time", msgArriveTime);
	}
	
	public java.util.Date getMsgArriveTime() {
		return get("msg_arrive_time");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setX2ip(java.lang.String x2ip) {
		set("x2ip", x2ip);
	}
	
	public java.lang.String getX2ip() {
		return getStr("x2ip");
	}

	public void setX2port(java.lang.String x2port) {
		set("x2port", x2port);
	}
	
	public java.lang.String getX2port() {
		return getStr("x2port");
	}

	public void setX3ip(java.lang.String x3ip) {
		set("x3ip", x3ip);
	}
	
	public java.lang.String getX3ip() {
		return getStr("x3ip");
	}

	public void setX3port(java.lang.String x3port) {
		set("x3port", x3port);
	}
	
	public java.lang.String getX3port() {
		return getStr("x3port");
	}

	public void setMonType(java.lang.String monType) {
		set("mon_type", monType);
	}
	
	public java.lang.String getMonType() {
		return getStr("mon_type");
	}

	public void setAddType(java.lang.String addType) {
		set("add_type", addType);
	}
	
	public java.lang.String getAddType() {
		return getStr("add_type");
	}

	public void setAdd(java.lang.String add) {
		set("add", add);
	}
	
	public java.lang.String getAdd() {
		return getStr("add");
	}

	public void setTp(java.lang.String tp) {
		set("tp", tp);
	}
	
	public java.lang.String getTp() {
		return getStr("tp");
	}

	public void setAppBizType(java.lang.String appBizType) {
		set("app_biz_type", appBizType);
	}
	
	public java.lang.String getAppBizType() {
		return getStr("app_biz_type");
	}

	public void setLnsAdd(java.lang.String lnsAdd) {
		set("lns_add", lnsAdd);
	}
	
	public java.lang.String getLnsAdd() {
		return getStr("lns_add");
	}

}
