package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskList<M extends BaseTaskList<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setType(Integer type) {
		set("type", type);
	}
	
	public Integer getType() {
		return getInt("type");
	}

	public void setRefId(Integer refId) {
		set("refId", refId);
	}
	
	public Integer getRefId() {
		return getInt("refId");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}
	
	public Integer getStatus() {
		return getInt("status");
	}

	public void setMsg(String msg) {
		set("msg", msg);
	}
	
	public String getMsg() {
		return getStr("msg");
	}

}
