package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseFlowMsg<M extends BaseBaseFlowMsg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setFlowId(java.lang.Integer flowId) {
		set("flow_id", flowId);
	}
	
	public java.lang.Integer getFlowId() {
		return getInt("flow_id");
	}

	public void setPort(java.lang.String port) {
		set("port", port);
	}
	
	public java.lang.String getPort() {
		return getStr("port");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public void setTaxis(java.lang.Integer taxis) {
		set("taxis", taxis);
	}
	
	public java.lang.Integer getTaxis() {
		return getInt("taxis");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setUnitId(java.lang.String unitId) {
		set("unit_id", unitId);
	}
	
	public java.lang.String getUnitId() {
		return getStr("unit_id");
	}

	public void setDirection(java.lang.String direction) {
		set("direction", direction);
	}
	
	public java.lang.String getDirection() {
		return getStr("direction");
	}

	public void setMsgType(java.lang.String msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.String getMsgType() {
		return getStr("msg_type");
	}

}
