package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsgTemplet<M extends BaseMsgTemplet<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setTempletName(String templetName) {
		set("templet_name", templetName);
	}

	public String getTempletName() {
		return get("templet_name");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setLicId(String licId) {
		set("lic_id", licId);
	}

	public String getLicId() {
		return get("lic_id");
	}

	public void setMsisdn(String msisdn) {
		set("msisdn", msisdn);
	}

	public String getMsisdn() {
		return get("msisdn");
	}

	public void setImei(String imei) {
		set("imei", imei);
	}

	public String getImei() {
		return get("imei");
	}

	public void setImsi(String imsi) {
		set("imsi", imsi);
	}

	public String getImsi() {
		return get("imsi");
	}

	public void setProposeType(String proposeType) {
		set("propose_type", proposeType);
	}

	public String getProposeType() {
		return get("propose_type");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(String modifyBy) {
		set("modify_by", modifyBy);
	}

	public String getModifyBy() {
		return get("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setEventSn(String eventSn) {
		set("event_sn", eventSn);
	}

	public String getEventSn() {
		return get("event_sn");
	}

	public void setCallSn(Integer callSn) {
		set("call_sn", callSn);
	}

	public Integer getCallSn() {
		return get("call_sn");
	}

	public void setCallSnChild(Integer callSnChild) {
		set("call_sn_child", callSnChild);
	}

	public Integer getCallSnChild() {
		return get("call_sn_child");
	}

	public void setGummeid(String gummeid) {
		set("gummeid", gummeid);
	}

	public String getGummeid() {
		return get("gummeid");
	}

	public void setLai(String lai) {
		set("lai", lai);
	}

	public String getLai() {
		return get("lai");
	}

	public void setLastVisitedTai(String lastVisitedTai) {
		set("last_visited_tai", lastVisitedTai);
	}

	public String getLastVisitedTai() {
		return get("last_visited_tai");
	}

	public void setTaiList(String taiList) {
		set("tai_list", taiList);
	}

	public String getTaiList() {
		return get("tai_list");
	}

	public void setEcgi(String ecgi) {
		set("ecgi", ecgi);
	}

	public String getEcgi() {
		return get("ecgi");
	}

	public void setOldMmeSgsn(String oldMmeSgsn) {
		set("old_mme_sgsn", oldMmeSgsn);
	}

	public String getOldMmeSgsn() {
		return get("old_mme_sgsn");
	}

	public void setGuti(String guti) {
		set("guti", guti);
	}

	public String getGuti() {
		return get("guti");
	}

}
