package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDownload<M extends BaseDownload<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setFileName(String fileName) {
		set("fileName", fileName);
	}
	
	public String getFileName() {
		return getStr("fileName");
	}

	public void setDescr(String descr) {
		set("descr", descr);
	}
	
	public String getDescr() {
		return getStr("descr");
	}

	public void setFileType(String fileType) {
		set("fileType", fileType);
	}
	
	public String getFileType() {
		return getStr("fileType");
	}

	public void setSize(String size) {
		set("size", size);
	}
	
	public String getSize() {
		return getStr("size");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setPath(String path) {
		set("path", path);
	}
	
	public String getPath() {
		return getStr("path");
	}

	public void setDownloadCount(Integer downloadCount) {
		set("downloadCount", downloadCount);
	}
	
	public Integer getDownloadCount() {
		return getInt("downloadCount");
	}

	public void setIsShow(Integer isShow) {
		set("isShow", isShow);
	}
	
	public Integer getIsShow() {
		return getInt("isShow");
	}

}
