package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionCopy1<M extends BaseQuestionCopy1<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setQuestionId(String questionId) {
		set("questionId", questionId);
	}

	public String getQuestionId() {
		return get("questionId");
	}

	public void setQuestionTitle(String questionTitle) {
		set("questionTitle", questionTitle);
	}

	public String getQuestionTitle() {
		return get("questionTitle");
	}

	public void setQuestionItems(String questionItems) {
		set("questionItems", questionItems);
	}

	public String getQuestionItems() {
		return get("questionItems");
	}

	public void setQuestionAnswer(String questionAnswer) {
		set("questionAnswer", questionAnswer);
	}

	public String getQuestionAnswer() {
		return get("questionAnswer");
	}

	public void setQuestionType(String questionType) {
		set("questionType", questionType);
	}

	public String getQuestionType() {
		return get("questionType");
	}

	public void setKeywords(String keywords) {
		set("keywords", keywords);
	}

	public String getKeywords() {
		return get("keywords");
	}

	public void setIsPassed(String isPassed) {
		set("isPassed", isPassed);
	}

	public String getIsPassed() {
		return get("isPassed");
	}

	public void setCreateBy(String createBy) {
		set("createBy", createBy);
	}

	public String getCreateBy() {
		return get("createBy");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setModifyBy(String modifyBy) {
		set("modifyBy", modifyBy);
	}

	public String getModifyBy() {
		return get("modifyBy");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modifyTime", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modifyTime");
	}

	public void setAuditBy(String auditBy) {
		set("auditBy", auditBy);
	}

	public String getAuditBy() {
		return get("auditBy");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("auditTime", auditTime);
	}

	public java.util.Date getAuditTime() {
		return get("auditTime");
	}

}
