package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseX1msg<M extends BaseX1msg<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUnit(String unit) {
		set("unit", unit);
	}

	public String getUnit() {
		return get("unit");
	}

	public void setMsgType(String msgType) {
		set("msg_type", msgType);
	}

	public String getMsgType() {
		return get("msg_type");
	}

	public void setPerposeId(String perposeId) {
		set("perpose_id", perposeId);
	}

	public String getPerposeId() {
		return get("perpose_id");
	}

	public void setOperationResult(String operationResult) {
		set("operation_result", operationResult);
	}

	public String getOperationResult() {
		return get("operation_result");
	}

	public void setMsgArriveTime(java.util.Date msgArriveTime) {
		set("msg_arrive_time", msgArriveTime);
	}

	public java.util.Date getMsgArriveTime() {
		return get("msg_arrive_time");
	}

	public void setCreator(String creator) {
		set("creator", creator);
	}

	public String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(String modifyBy) {
		set("modify_by", modifyBy);
	}

	public String getModifyBy() {
		return get("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setX2ip(String x2ip) {
		set("x2ip", x2ip);
	}

	public String getX2ip() {
		return get("x2ip");
	}

	public void setX2port(String x2port) {
		set("x2port", x2port);
	}

	public String getX2port() {
		return get("x2port");
	}

	public void setX3ip(String x3ip) {
		set("x3ip", x3ip);
	}

	public String getX3ip() {
		return get("x3ip");
	}

	public void setX3port(String x3port) {
		set("x3port", x3port);
	}

	public String getX3port() {
		return get("x3port");
	}

	public void setMonType(String monType) {
		set("mon_type", monType);
	}

	public String getMonType() {
		return get("mon_type");
	}

	public void setAddType(String addType) {
		set("add_type", addType);
	}

	public String getAddType() {
		return get("add_type");
	}

	public void setAdd(String add) {
		set("add", add);
	}

	public String getAdd() {
		return get("add");
	}

	public void setTp(String tp) {
		set("tp", tp);
	}

	public String getTp() {
		return get("tp");
	}

	public void setAppBizType(String appBizType) {
		set("app_biz_type", appBizType);
	}

	public String getAppBizType() {
		return get("app_biz_type");
	}

	public void setLnsAdd(String lnsAdd) {
		set("lns_add", lnsAdd);
	}

	public String getLnsAdd() {
		return get("lns_add");
	}

}
