package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionFlow<M extends BaseQuestionFlow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setQuestionId(java.lang.Integer questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.String getUnitId() {
		return getStr("unit_id");
	}

	public void setUnitId(java.lang.String unitId) {
		set("unit_id", unitId);
	}

	public java.lang.Integer getQuestionId() {
		return getInt("question_id");
	}

	public void setPort(java.lang.String port) {
		set("port", port);
	}
	
	public java.lang.String getPort() {
		return getStr("port");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

	public void setTaxis(java.lang.Integer taxis) {
		set("taxis", taxis);
	}
	
	public java.lang.Integer getTaxis() {
		return getInt("taxis");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyBy(java.lang.String modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.String getModifyBy() {
		return getStr("modify_by");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setRelationId(java.lang.String relationId) {
		set("relationId", relationId);
	}
	
	public java.lang.String getRelationId() {
		return getStr("relationId");
	}

}
