package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNumber<M extends BaseNumber<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMsisdn(java.lang.String msisdn) {
		set("msisdn", msisdn);
	}
	
	public java.lang.String getMsisdn() {
		return getStr("msisdn");
	}

	public void setImsi(java.lang.String imsi) {
		set("imsi", imsi);
	}
	
	public java.lang.String getImsi() {
		return getStr("imsi");
	}

	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}
	
	public java.lang.String getImei() {
		return getStr("imei");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setNumberFormat(java.lang.String numberFormat) {
		set("number_format", numberFormat);
	}
	
	public java.lang.String getNumberFormat() {
		return getStr("number_format");
	}

	public void setLicId(java.lang.String licId) {
		set("lic_id", licId);
	}
	
	public java.lang.String getLicId() {
		return getStr("lic_id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setIpTime(java.lang.String ipTime) {
		set("ip_time", ipTime);
	}
	
	public java.lang.String getIpTime() {
		return getStr("ip_time");
	}

	public void setIpPort(java.lang.String ipPort) {
		set("ip_port", ipPort);
	}
	
	public java.lang.String getIpPort() {
		return getStr("ip_port");
	}

	public void setIpAddressField(java.lang.String ipAddressField) {
		set("ip_address_field", ipAddressField);
	}
	
	public java.lang.String getIpAddressField() {
		return getStr("ip_address_field");
	}

	public void setNai(java.lang.String nai) {
		set("nai", nai);
	}
	
	public java.lang.String getNai() {
		return getStr("nai");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
	}
	
	public java.lang.String getPhoneNumber() {
		return getStr("phone_number");
	}

	public void setSip(java.lang.String sip) {
		set("sip", sip);
	}
	
	public java.lang.String getSip() {
		return getStr("sip");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setX2ip(java.lang.String x2ip) {
		set("x2ip", x2ip);
	}
	
	public java.lang.String getX2ip() {
		return getStr("x2ip");
	}

	public void setX2port(java.lang.String x2port) {
		set("x2port", x2port);
	}
	
	public java.lang.String getX2port() {
		return getStr("x2port");
	}

	public void setX3ip(java.lang.String x3ip) {
		set("x3ip", x3ip);
	}
	
	public java.lang.String getX3ip() {
		return getStr("x3ip");
	}

	public void setX3port(java.lang.String x3port) {
		set("x3port", x3port);
	}
	
	public java.lang.String getX3port() {
		return getStr("x3port");
	}

	public void setMonType(java.lang.String monType) {
		set("mon_type", monType);
	}
	
	public java.lang.String getMonType() {
		return getStr("mon_type");
	}

	public void setAddType(java.lang.String addType) {
		set("add_type", addType);
	}
	
	public java.lang.String getAddType() {
		return getStr("add_type");
	}

	public void setAdd(java.lang.String add) {
		set("add", add);
	}
	
	public java.lang.String getAdd() {
		return getStr("add");
	}

	public void setTp(java.lang.String tp) {
		set("tp", tp);
	}
	
	public java.lang.String getTp() {
		return getStr("tp");
	}

	public void setAppBizType(java.lang.String appBizType) {
		set("app_biz_type", appBizType);
	}
	
	public java.lang.String getAppBizType() {
		return getStr("app_biz_type");
	}

	public void setLnsAdd(java.lang.String lnsAdd) {
		set("lns_add", lnsAdd);
	}
	
	public java.lang.String getLnsAdd() {
		return getStr("lns_add");
	}

	public void setSn1(java.lang.Integer sn1) {
		set("sn1", sn1);
	}
	
	public java.lang.Integer getSn1() {
		return getInt("sn1");
	}

	public void setSn2(java.lang.Integer sn2) {
		set("sn2", sn2);
	}
	
	public java.lang.Integer getSn2() {
		return getInt("sn2");
	}

	public void setImpi(java.lang.String impi) {
		set("impi", impi);
	}
	
	public java.lang.String getImpi() {
		return getStr("impi");
	}

}
