package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResourceType<M extends BaseResourceType<M>> extends Model<M> implements IBean {

	public void setTypeId(java.lang.String typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.String getTypeId() {
		return getStr("type_id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public void setTypeDesc(java.lang.Integer typeDesc) {
		set("type_desc", typeDesc);
	}
	
	public java.lang.Integer getTypeDesc() {
		return getInt("type_desc");
	}

	public void setIsShow(java.lang.String isShow) {
		set("is_show", isShow);
	}
	
	public java.lang.String getIsShow() {
		return getStr("is_show");
	}

	public void setPTypeId(java.lang.String pTypeId) {
		set("p_type_id", pTypeId);
	}
	
	public java.lang.String getPTypeId() {
		return getStr("p_type_id");
	}

}
