package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	public void setID(String ID) {
		set("ID", ID);
	}

	public String getID() {
		return get("ID");
	}

	public void setSeq(java.math.BigDecimal seq) {
		set("seq", seq);
	}

	public java.math.BigDecimal getSeq() {
		return get("seq");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return get("text");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setPid(String pid) {
		set("pid", pid);
	}

	public String getPid() {
		return get("pid");
	}

}
