package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswerLog<M extends BaseAnswerLog<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setExamName(String examName) {
		set("exam_name", examName);
	}

	public String getExamName() {
		return get("exam_name");
	}

	public void setAccountId(Integer accountId) {
		set("account_id", accountId);
	}

	public Integer getAccountId() {
		return get("account_id");
	}

	public void setAnswerNo(String answerNo) {
		set("answer_no", answerNo);
	}

	public String getAnswerNo() {
		return get("answer_no");
	}

	public void setAnswerBegin(java.util.Date answerBegin) {
		set("answer_begin", answerBegin);
	}

	public java.util.Date getAnswerBegin() {
		return get("answer_begin");
	}

	public void setAnswerEnd(java.util.Date answerEnd) {
		set("answer_end", answerEnd);
	}

	public java.util.Date getAnswerEnd() {
		return get("answer_end");
	}

	public void setExamScore(Double examScore) {
		set("exam_score", examScore);
	}

	public Double getExamScore() {
		return get("exam_score");
	}

	public void setUserScore(Double userScore) {
		set("user_score", userScore);
	}

	public Double getUserScore() {
		return get("user_score");
	}

	public void setOfficialId(Integer officialId) {
		set("official_id", officialId);
	}

	public Integer getOfficialId() {
		return get("official_id");
	}

	public void setJudgeTime(java.util.Date judgeTime) {
		set("judge_time", judgeTime);
	}

	public java.util.Date getJudgeTime() {
		return get("judge_time");
	}

}
