package com.jfinal.club.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBug<M extends BaseBug<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return get("id");
	}

	public void setCreatedatetime(java.util.Date createdatetime) {
		set("createdatetime", createdatetime);
	}

	public java.util.Date getCreatedatetime() {
		return get("createdatetime");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setNote(String note) {
		set("note", note);
	}

	public String getNote() {
		return get("note");
	}

}
